version: '3.3'
services:
  postgres:
    image: 'postgres:14'
    container_name: 'tarifficator_app'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=tarifficator'