name: backend
version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
  tarifficator-db:
    image: 'postgres:14'
    container_name: tarifficator-db
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=tarifficator'
  account-service:
    container_name: account-service
    ports:
      - "8081:8081"
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: account-service/target/account-service-0.0.1-SNAPSHOT-exec.jar
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tarifficator-db:5432/tarifficator
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - tarifficator-db
  tariff-service:
    container_name: tariff-service
    ports:
      - "8082:8082"
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: tariff-service/target/tariff-service-0.0.1-SNAPSHOT-exec.jar
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tarifficator-db:5432/tarifficator
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - tarifficator-db
      - kafka
  product-service:
    container_name: product-service
    ports:
      - "8083:8083"
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: product-service/target/product-service-0.0.1-SNAPSHOT-exec.jar
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tarifficator-db:5432/tarifficator
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - tarifficator-db
      - kafka
  client-service:
    container_name: client-service
    ports:
      - "8084:8084"
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: client-service/target/client-service-0.0.1-SNAPSHOT-exec.jar
    environment:
      - BANK_USER_SERVICE_URI=http://account-service:8081
      - BANK_TARIFF_SERVICE_URI=http://tariff-service:8082
      - BANK_PRODUCT_SERVICE_URI=http://product-service:8083